POST http://127.0.0.1:8888/articles
Content-Type: application/json

{
  "title": "First Article",
  "body": "This is the body of the first article."
}

###

GET http://127.0.0.1:8888/articles
Accept: application/json

###

GET http://127.0.0.1:8888/articles/1
Accept: application/json

###

GET http://127.0.0.1:8888/articles/999
Accept: application/json

###

PUT http://127.0.0.1:8888/articles/1
Content-Type: application/json

{
  "title": "Updated First Article",
  "body": "This is the updated body of the first article."
}

###

DELETE http://127.0.0.1:8888/articles/1

###

DELETE http://127.0.0.1:8888/articles/999

